This notebook is created to add headers to the GO_terms.tsv files and to the ones inside the networks folder. To accomplish this, a few lines in bash will be needed, it can also be added using python, but it is easier to add a line at the beginning of a file with bash than to read the whole file with python and modify it.

In [6]:
%%bash

# Adding header GO file. Note we are modifying inplace
sed -i '1s/^/category\tGO\tgo_description\n/' GO_terms.tsv
head GO_terms.tsv

category	GO	go_description
BIOLOGICAL_PROCESS	GO:0000041	transition metal ion transport
BIOLOGICAL_PROCESS	GO:0000103	sulfate assimilation
BIOLOGICAL_PROCESS	GO:0000105	histidine biosynthetic process
BIOLOGICAL_PROCESS	GO:0000160	phosphorelay signal transduction system
BIOLOGICAL_PROCESS	GO:0000162	tryptophan biosynthetic process
BIOLOGICAL_PROCESS	GO:0000256	allantoin catabolic process
BIOLOGICAL_PROCESS	GO:0000271	polysaccharide biosynthetic process
BIOLOGICAL_PROCESS	GO:0000272	polysaccharide catabolic process
BIOLOGICAL_PROCESS	GO:0000413	protein peptidyl-prolyl isomerization

In [16]:
%%bash

# We are gonna do the same for the networks

# 1. The id of this interaction
# 2. Transcription Factor TF
# 3. Target TG
# 4. Status of the interactions (is it known or is it new?)
# 5. Organism where that interaction was mapped
# 6. id of the interaction mapped in the organism where that interaction was mapped
# 7. Total organism where that interaction came from
# 8. Foward or Reverse string
# 9. Transcription Unit id of the target

for net in networks/*tsv; do
    
    sed -i '1s/^/id_net\ttf\ttg\tstatus\torg_reference\tid_net_reference\tcount_org_reference\tstring\ttu_unit\n/' "${net}"

done

In [17]:
from pandas import read_csv

In [18]:
file = "networks/GCF_000005845.2_E_coli_K12_genomic_extended_network_plus_TU.tsv"
read_csv(file, sep="\t", nrows=10)

,id_net,tf,tg,status,org_reference,id_net_reference,count_org_reference,string,tu_unit
0,2980,NP_414561.1,NP_414560.1,Known,Salmon,1758,1.0,F,1_tu
1,2981,NP_414561.1,NP_414561.1,Known,Salmon,1759,1.0,F,1_tu
2,2986,NP_414561.1,NP_415540.1,Known,NOT_REFR_ORG,NOT_REFR_NUM,NaN,R,2_tu
3,2985,NP_414561.1,NP_415541.1,Known,NOT_REFR_ORG,NOT_REFR_NUM,NaN,R,2_tu
4,2984,NP_414561.1,NP_415542.1,Known,NOT_REFR_ORG,NOT_REFR_NUM,NaN,R,2_tu
5,2983,NP_414561.1,NP_415543.1,Known,NOT_REFR_ORG,NOT_REFR_NUM,NaN,R,2_tu
6,2982,NP_414561.1,NP_415999.1,Known,NOT_REFR_ORG,NOT_REFR_NUM,NaN,F,3_tu
7,958,NP_414576.4,NP_414577.2,Known,Salmon,2910,1.0,R,4_tu
8,957,NP_414576.4,NP_414578.2,Known,Salmon,2911,1.0,R,4_tu
9,956,NP_414576.4,NP_414579.4,Known,Salmon,2912,1.0,R,5_tu